using System;

namespace Judge.Interop
{
    [Flags]
    public enum JobObjectLimitFlags : uint
    {
        JOB_OBJECT_LIMIT_ACTIVE_PROCESS = 8,
        JOB_OBJECT_LIMIT_AFFINITY = 16,
        JOB_OBJECT_LIMIT_BREAKAWAY_OK = 2048,
        JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION = 1024,
        JOB_OBJECT_LIMIT_JOB_MEMORY = 512,
        JOB_OBJECT_LIMIT_JOB_TIME = 4,
        JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE = 8192,
        JOB_OBJECT_LIMIT_PRESERVE_JOB_TIME = 64,
        JOB_OBJECT_LIMIT_PRIORITY_CLASS = 32,
        JOB_OBJECT_LIMIT_PROCESS_MEMORY = 256,
        JOB_OBJECT_LIMIT_PROCESS_TIME = 2,
        JOB_OBJECT_LIMIT_SCHEDULING_CLASS = 128,
        JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK = 4096,
        JOB_OBJECT_LIMIT_WORKINGSET = 1,
    }
}